const theme = {
    button: {
        link: {
            blue: {
                outline: {
                    color: '#1e6c82',    
                    backgroundColor: 'transparent',
                    borderColor: '#1e6c82',
                    cursor: 'pointer',
                    margin: 0,
                    display: 'inline-block',
                    textAlign: 'center',
                    whiteSpace: 'nowrap',
                    border: '1px solid transparent',
                    fontSize: '1rem',
                    fontWeight: 400,
                    padding: '.375rem .75rem',
                    textDecoration: 'none'
                },
                default: {
                    color: 'white',    
                    backgroundColor: '#1e6c82',
                    borderColor: '#1e6c82',
                    cursor: 'pointer',
                    margin: 0,
                    display: 'inline-block',
                    textAlign: 'center',
                    whiteSpace: 'nowrap',
                    border: '1px solid transparent',
                    fontSize: '1rem',
                    fontWeight: 400,
                    padding: '.375rem .75rem',
                    textDecoration: 'none'
                },
                text: {
                    fontFamily: `'Lato', 'Helvetica Neue', Arial, Helvetica, sans-serif`,
                    color: '#1e6c82',
                    backgroundColor: 'transparent',
                    cursor: 'pointer',
                    margin: 0,
                    display: 'inline-block',
                    textAlign: 'center',
                    whiteSpace: 'nowrap',
                    border: '1px solid transparent',
                    fontSize: '1rem',
                    fontWeight: 400,
                    padding: '.375rem .75rem',
                    textDecoration: 'none'
                }
            },
            orange: {
                outline: {
                    color: '#be6046',    
                    backgroundColor: 'transparent',
                    borderColor: '#be6046',
                    cursor: 'pointer',
                    margin: 0,
                    display: 'inline-block',
                    textAlign: 'center',
                    whiteSpace: 'nowrap',
                    border: '1px solid transparent',
                    fontSize: '1rem',
                    fontWeight: 400,
                    padding: '.375rem .75rem',
                    textDecoration: 'none'
                },
                default: {
                    color: 'white',    
                    backgroundColor: '#be6046',
                    borderColor: '#be6046',
                    cursor: 'pointer',
                    margin: 0,
                    display: 'inline-block',
                    textAlign: 'center',
                    whiteSpace: 'nowrap',
                    border: '1px solid transparent',
                    fontSize: '1rem',
                    fontWeight: 400,
                    padding: '.375rem .75rem',
                    textDecoration: 'none'
                },
                text: {
                    color: '#be6046',
                    backgroundColor: 'transparent',
                    cursor: 'pointer',
                    margin: 0,
                    display: 'inline-block',
                    textAlign: 'center',
                    whiteSpace: 'nowrap',
                    border: '1px solid transparent',
                    fontSize: '1rem',
                    fontWeight: 400,
                    padding: '.375rem .75rem',
                    textDecoration: 'none'
                },
                fontFamily: `'Lato', 'Helvetica Neue', Arial, Helvetica, sans-serif`,
            },
            danger: {
                outline: {
                    color: '#F2545B',    
                    backgroundColor: 'transparent',
                    borderColor: '#F2545B',
                    cursor: 'pointer',
                    margin: 0,
                    display: 'inline-block',
                    textAlign: 'center',
                    whiteSpace: 'nowrap',
                    border: '1px solid transparent',
                    fontSize: '1rem',
                    fontWeight: 400,
                    padding: '.375rem .75rem',
                    textDecoration: 'none'
                },
                default: {
                    color: 'white',    
                    backgroundColor: '#F2545B',
                    borderColor: '#F2545B',
                    cursor: 'pointer',
                    margin: 0,
                    display: 'inline-block',
                    textAlign: 'center',
                    whiteSpace: 'nowrap',
                    border: '1px solid transparent',
                    fontSize: '1rem',
                    fontWeight: 400,
                    padding: '.375rem .75rem',
                    textDecoration: 'none'
                },
                text: {
                    color: '#F2545B',
                    backgroundColor: 'transparent',
                    cursor: 'pointer',
                    margin: 0,
                    display: 'inline-block',
                    textAlign: 'center',
                    whiteSpace: 'nowrap',
                    border: '1px solid transparent',
                    fontSize: '1rem',
                    fontWeight: 400,
                    padding: '.375rem .75rem',
                    textDecoration: 'none'
                },
                fontFamily: `'Lato', 'Helvetica Neue', Arial, Helvetica, sans-serif`,
            },
            success: {
                outline: {
                    color: '#63A375',    
                    backgroundColor: 'transparent',
                    borderColor: '#63A375',
                    cursor: 'pointer',
                    margin: 0,
                    display: 'inline-block',
                    textAlign: 'center',
                    whiteSpace: 'nowrap',
                    border: '1px solid transparent',
                    fontSize: '1rem',
                    fontWeight: 400,
                    padding: '.375rem .75rem',
                    textDecoration: 'none'
                },
                default: {
                    color: 'white',    
                    backgroundColor: '#63A375',
                    borderColor: '#63A375',
                    cursor: 'pointer',
                    margin: 0,
                    display: 'inline-block',
                    textAlign: 'center',
                    whiteSpace: 'nowrap',
                    border: '1px solid transparent',
                    fontSize: '1rem',
                    fontWeight: 400,
                    padding: '.375rem .75rem',
                    textDecoration: 'none'
                },
                text: {
                    color: '#63A375',
                    backgroundColor: 'transparent',
                    cursor: 'pointer',
                    margin: 0,
                    display: 'inline-block',
                    textAlign: 'center',
                    whiteSpace: 'nowrap',
                    border: '1px solid transparent',
                    fontSize: '1rem',
                    fontWeight: 400,
                    padding: '.375rem .75rem',
                    textDecoration: 'none'
                },
                fontFamily: `'Lato', 'Helvetica Neue', Arial, Helvetica, sans-serif`,
            }
        },
        blue: {
            outline: {
                color: '#1e6c82',    
                backgroundColor: 'transparent',
                borderColor: '#1e6c82',
                cursor: 'pointer',
                margin: 0,
                display: 'inline-block',
                textAlign: 'center',
                whiteSpace: 'nowrap',
                border: '1px solid transparent',
                fontSize: '1rem',
                fontWeight: 400,
                padding: '.375rem .75rem'
            },
            default: {
                color: 'white',    
                backgroundColor: '#1e6c82',
                borderColor: '#1e6c82',
                cursor: 'pointer',
                margin: 0,
                display: 'inline-block',
                textAlign: 'center',
                whiteSpace: 'nowrap',
                border: '1px solid transparent',
                fontSize: '1rem',
                fontWeight: 400,
                padding: '.375rem .75rem'
            },
            text: {
                color: '#1e6c82',
                backgroundColor: 'transparent',
                cursor: 'pointer',
                margin: 0,
                display: 'inline-block',
                textAlign: 'center',
                whiteSpace: 'nowrap',
                border: '1px solid transparent',
                fontSize: '1rem',
                fontWeight: 400,
                padding: '.375rem .75rem'
            },
            fontFamily: `'Lato', 'Helvetica Neue', Arial, Helvetica, sans-serif`,
        },
        orange: {
            outline: {
                color: '#be6046',    
                backgroundColor: 'transparent',
                borderColor: '#be6046',
                cursor: 'pointer',
                margin: 0,
                display: 'inline-block',
                textAlign: 'center',
                whiteSpace: 'nowrap',
                border: '1px solid transparent',
                fontSize: '1rem',
                fontWeight: 400,
                padding: '.375rem .75rem'
            },
            default: {
                color: 'white',    
                backgroundColor: '#be6046',
                borderColor: '#be6046',
                cursor: 'pointer',
                margin: 0,
                display: 'inline-block',
                textAlign: 'center',
                whiteSpace: 'nowrap',
                border: '1px solid transparent',
                fontSize: '1rem',
                fontWeight: 400,
                padding: '.375rem .75rem'
            },
            text: {
                color: '#be6046',
                backgroundColor: 'transparent',
                cursor: 'pointer',
                margin: 0,
                display: 'inline-block',
                textAlign: 'center',
                whiteSpace: 'nowrap',
                border: '1px solid transparent',
                fontSize: '1rem',
                fontWeight: 400,
                padding: '.375rem .75rem'
            },
            fontFamily: `'Lato', 'Helvetica Neue', Arial, Helvetica, sans-serif`,
        },
        danger: {
            outline: {
                color: '#F2545B',    
                backgroundColor: 'transparent',
                borderColor: '#F2545B',
                cursor: 'pointer',
                margin: 0,
                display: 'inline-block',
                textAlign: 'center',
                whiteSpace: 'nowrap',
                border: '1px solid transparent',
                fontSize: '1rem',
                fontWeight: 400,
                padding: '.375rem .75rem'
            },
            default: {
                color: 'white',    
                backgroundColor: '#F2545B',
                borderColor: '#F2545B',
                cursor: 'pointer',
                margin: 0,
                display: 'inline-block',
                textAlign: 'center',
                whiteSpace: 'nowrap',
                border: '1px solid transparent',
                fontSize: '1rem',
                fontWeight: 400,
                padding: '.375rem .75rem'
            },
            text: {
                color: '#F2545B',
                backgroundColor: 'transparent',
                cursor: 'pointer',
                margin: 0,
                display: 'inline-block',
                textAlign: 'center',
                whiteSpace: 'nowrap',
                border: '1px solid transparent',
                fontSize: '1rem',
                fontWeight: 400,
                padding: '.375rem .75rem'
            },
            fontFamily: `'Lato', 'Helvetica Neue', Arial, Helvetica, sans-serif`,
        },
        success: {
            outline: {
                color: '#63A375',    
                backgroundColor: 'transparent',
                borderColor: '#63A375',
                cursor: 'pointer',
                margin: 0,
                display: 'inline-block',
                textAlign: 'center',
                whiteSpace: 'nowrap',
                border: '1px solid transparent',
                fontSize: '1rem',
                fontWeight: 400,
                padding: '.375rem .75rem'
            },
            default: {
                color: 'white',    
                backgroundColor: '#63A375',
                borderColor: '#63A375',
                cursor: 'pointer',
                margin: 0,
                display: 'inline-block',
                textAlign: 'center',
                whiteSpace: 'nowrap',
                border: '1px solid transparent',
                fontSize: '1rem',
                fontWeight: 400,
                padding: '.375rem .75rem'
            },
            text: {
                color: '#63A375',
                backgroundColor: 'transparent',
                cursor: 'pointer',
                margin: 0,
                display: 'inline-block',
                textAlign: 'center',
                whiteSpace: 'nowrap',
                border: '1px solid transparent',
                fontSize: '1rem',
                fontWeight: 400,
                padding: '.375rem .75rem'
            },
            fontFamily: `'Lato', 'Helvetica Neue', Arial, Helvetica, sans-serif`,
        }
    }
};

export default theme;